###
POST http://localhost:8000/articles
Content-Type: application/json

{
  "title": "애플 맥북 얼마에 팔아요?",
  "content": "2023년도 맥북 얼마에 파는 게 좋을까요?"
}

###
GET http://localhost:8000/articles?limit=100

###
PATCH http://localhost:8000/articles/8f02ccce-2be2-4dfd-b8b9-4be79ff81b05
Content-Type: application/json

{
  "title": "올리브 오일은 언제 상하나요?",
  "content": "올리브 오일은 올리브 기름을 말하는 것입니다. 하지만 올리브 오일이라고 부릅니다. 그것은 상하지만 상하지 않습니다. 결구 자연으로 돌아가 다른 올리브를 생성할 것이기 때문입니다."
}

###
GET http://localhost:8000/articles?order=oldest&limit=3


# 게시글 댓글 목록 조회
###
GET http://localhost:8000/articles?keyword=증권

###
DELETE  http://localhost:8000/articles/

# 게시글 댓글 목록 조회
###
GET http://localhost:8000/articles/2cbe8fe7-6014-4c3a-b019-31f05be94a8f/comments

# 게시글 댓글 등록
###
POST http://localhost:8000/articles/2cbe8fe7-6014-4c3a-b019-31f05be94a8f/comments
Content-Type: application/json

{
  "content": "매우 잘 자는 방법은 매우 힘들게 운동을 하고 자는 것이라고 생각하기 쉬운데 오히려 더 잠이 안 올수도 있다고 생각되지만 그래도 피곤하면 자게 돼 있죠.."
}
