###

GET http://localhost:8000/products

###

GET http://localhost:8000/products?order=best&limit=3

###

GET http://localhost:8000/products/53e744ef-5309-4d20-8bdc-d417bc7c1249

###
POST http://localhost:8000/products
Content-Type: application/json

{
  "name": "독서 필사의 중요성",
  "description": "독서라는 매우 힘든 과정일 수 있습니다. 그렇기 때문에 그 내용이 한번에 이해되기는 쉽지 않기 때문에 노트북 필사를 통해 그 글을 쓰게 된 회로를 이해하는 것이 중요합니다.",
  "price": 10055400,
  "tags": ["필사", "독서", "노트북", "꾸준히"]
}


###
PATCH  http://localhost:8000/products/83c274c7-3ed1-4e69-83b1-d3f7a55b027c
Content-Type: application/json

{
    "name": "올리브오일",
    "description": "올리브 오일은 올리브 기름을 말하는 것입니다. 하지만 올리브 오일이라고 부릅니다.",
    "price": 8000,
    "tags": ["올리브", "오일", "올리브 오일"]
}

###

DELETE  http://localhost:8000/products/53e744ef-5309-4d20-8bdc-d417bc7c1249