
GET http://localhost:8000/db/tasks

###

PATCH  http://localhost:8000/db/tasks/6721de31af799ac0bde66355

###
GET http://localhost:8000/db/tasks/query?keyword=글자

###
DELETE http://localhost:8000/db/tasks/6721cf08af799ac0bde66353